In [1]:
'''Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Ans:-
    
Yes, there is a difference in the data type of variables list_ and array_list. list_ is a list object, while array_list is a numpy array object.
To print the data types of both variables, you can use the type() function.'''
#Ans:-

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))  
print(type(array_list))

This code will output the data types of list_ and array_list as list and numpy.ndarray respectively.


<class 'list'>
<class 'numpy.ndarray'>


In [2]:
'''Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.'''
# Ans:-

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)
print("Data types in list_:")
for element in list_:
    print(type(element))
print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
"""Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
# Ans:-
Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list. The np.array() function creates a new NumPy array object from the given list or tuple. The dtype parameter specifies the data type of the array elements. In this case, the int data type is specified for the array elements.
To print the data types of each element present in both the variables, list_ and array_list, you can use the type() function along with a loop as follows:"""
# Ans:-

import numpy as np

list_ = [1, 2.5, 'hello']
array_list = np.array(object=list_, dtype=int)
for element in list_:
    print(type(element))
for element in array_list:
    print(type(element))




In [5]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


In [8]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
Ans:-
Assuming that num_array is a NumPy array, here is the code to find its shape and size:'''
# Ans:-

import numpy as np
num_array = np.array([[1, 2], [3, 4], [5, 6]])
shape = num_array.shape
size = num_array.size
print("Shape of the array:", shape)
print("Size of the array:", size)

Here, the shape variable will contain a tuple (3, 2) which represents the shape of the array as 3 rows and 2 columns. 
The size variable will contain the total number of elements in the array, which is 6 in this case    
    

Shape of the array: (3, 2)
Size of the array: 6


In [9]:
"""Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]"""
# Ans:-
#Sure, here's the code to create a numpy array of a 3x3 matrix containing zeros only using the numpy array creation function:

import numpy as np
arr = np.zeros((3, 3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
# Ans:-

To create an identity matrix of shape (5,5) using NumPy functions, we can use the numpy.identity() function. This function takes a single argument, n, which specifies the size of the identity matrix to create.
Here's the code to create an identity matrix of shape (5,5) using NumPy:'''
# Ans:-

import numpy as np
identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
